In [6]:
import socket
import numpy as np
import jsonpickle

def from_bytes(b):
    """convert bytes back to python object.
    """
    j = b.decode('UTF-8')  # from bytes to json
    o = jsonpickle.decode(j)  # from json to python object
    return o

def up(port, fname):
    """send fname to server and retrieve corresponding results.
    
    # https://stackoverflow.com/questions/9382045/send-a-file-through-sockets-in-python
    """
    # create socket and connect
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect(('34.237.220.30', port)) 

    # send source to server
    with open(fname, "rb") as f:
        l = f.read(1024)
    s.send(l) 
        
    # receive results from server and unpack bytes to numpy
    res = s.recv(1024)
    o = from_bytes(res)  # https://markhneedham.com/blog/2018/04/07/python-serialize-deserialize-numpy-2d-arrays/
    # o = np.frombuffer(res)
    print(o)
    
    # close the connection 
    if res:
        s.close()
        return o
    else:
        raise ValueError

In [7]:
a = up(port=1111, fname="foobar.py")  # port should match server port

[[0.91100184 0.74885369 1.34420039 1.16293343]
 [0.70297936 0.87778659 1.15644492 1.2318245 ]
 [0.56951672 0.84942814 1.02202936 1.00972753]
 [0.28425611 0.80419118 0.86194495 1.11662609]]


In [ ]:
a